# Generated by Django 5.1.3 on 2024-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default/default-avatar.jpg', upload_to='profile/'),
        ),
    ]
