# Generated by Django 5.1.3 on 2024-12-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='add',
            new_name='ad',
        ),
    ]
