# Generated by Django 5.1.3 on 2024-12-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_chat_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('can_approve_ads', 'Can approve ads')]},
        ),
    ]
